services:
  - type: web
    name: avito-bot
    plan: free
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: "8553803161:AAFBMhAJVxiLZhQzXvifCXF_PMVvEb03g04"  # Вставь токен прямо здесь
      - key: YOUR_TELEGRAM_ID
        value: "1325037397"     # Вставь свой ID
      - key: CHECK_INTERVAL
        value: "30"
      - key: RAILPACK_PYTHON_VERSION
        value: "3.11.4"
